
import high.NewClass;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class jump extends javax.swing.JFrame {
int y=371;
int scr=0;
    /**
     * Creates new form jump
     */
    public jump() {
        initComponents();
        new NewClass();
        hsr.setText(""+NewClass.highscr);
        score.setEditable(false);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
         l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
         l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
         l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        homee.setVisible(false);
    }
int a=600;
int b=700;
int c=800;
int d=900;
int e1=1000;
int f=1100;
int g=1200;
int h=1300;
int a1=600;
int b1=700;
int c1=800;
int d1=900;
int e11=1000;
int f1=1100;
int g1=2000;
int h1=2100;

    public void reset()
    {
       
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
         l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
         l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
         l13.setVisible(false);
        l14.setVisible(false);
        l15.setVisible(false);
        l16.setVisible(false);
        homee.setVisible(true);
                a=600;
                b=700;
                c=800;
                d=900;
                e1=1000;
                f=1100;
                g=1200;
                h=1300;
                a1=600;
                b1=700;
                c1=800;
                d1=900;
                e11=1000;
                f1=1100;
                g1=1200;
                h1=1300;
                timer2.stop();
                timer3.stop();
                timer1.stop();
                 timer.stop();
                 
                 
                 y=370;
                  bot1.setBounds(290,370,30,20);
                  int s=p.nextInt(300);
                  t=p.nextInt(300);
                  u=p.nextInt(300);
v=p.nextInt(300);
s1=p.nextInt(300);
t1=p.nextInt(300);
u1=p.nextInt(300);
v1=p.nextInt(300);
s2=p.nextInt(300);
t2=p.nextInt(300);
u2=p.nextInt(300);
v2=p.nextInt(300);
s3=p.nextInt(300);
t3=p.nextInt(300);
u3=p.nextInt(300);
v3=p.nextInt(300);
click.setVisible(true);
  JOptionPane.showMessageDialog(null,"GAME OVER!  Your Score is : "+scr);
                  
                   if (scr>NewClass.highscr)
        {
            NewClass.highscr=scr;
              scr=0;
            setVisible(false);
        new scoree().setVisible(true);
        }
                    score.setText(""+0);
                 
    }
    public void t2res()
    {
                a=600;
                b=700;
                c=800;
                d=900;
                e1=1000;
                f=1100;
                g=1200;
                h=1300;
                
    }
    public void t3res()
    {           a1=600;
                b1=700;
                c1=800;
                d1=900;
                e11=1000;
                f1=1100;
                g1=1200;
                h1=1300;
    }

Random p=new Random();



int s=p.nextInt(300);
int t=p.nextInt(300);
int u=p.nextInt(300);
int v=p.nextInt(300);
int s1=p.nextInt(300);
int t1=p.nextInt(300);
int u1=p.nextInt(300);
int v1=p.nextInt(300);
int s2=p.nextInt(300);
int t2=p.nextInt(300);
int u2=p.nextInt(300);
int v2=p.nextInt(300);
int s3=p.nextInt(300);
int t3=p.nextInt(300);
int u3=p.nextInt(300);
int v3=p.nextInt(300);
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
int i=0;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        base1 = new javax.swing.JPanel();
        bot1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JPanel();
        homee = new javax.swing.JButton();
        score = new javax.swing.JTextField();
        l2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        l3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        l4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        l5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        l6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        l7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        l8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        l9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        l10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        l11 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        l12 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        l13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        l14 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        l15 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        l16 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        click = new javax.swing.JLabel();
        hsr = new javax.swing.JLabel();
        hsr1 = new javax.swing.JLabel();
        hsr2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        base1.setBackground(new java.awt.Color(0, 0, 0));
        base1.setMaximumSize(new java.awt.Dimension(600, 410));
        base1.setPreferredSize(new java.awt.Dimension(600, 410));
        base1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                base1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                base1MouseReleased(evt);
            }
        });

        bot1.setBackground(new java.awt.Color(0, 0, 0));
        bot1.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.jpg"))); // NOI18N

        javax.swing.GroupLayout bot1Layout = new javax.swing.GroupLayout(bot1);
        bot1.setLayout(bot1Layout);
        bot1Layout.setHorizontalGroup(
            bot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bot1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        bot1Layout.setVerticalGroup(
            bot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        l1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout l1Layout = new javax.swing.GroupLayout(l1);
        l1.setLayout(l1Layout);
        l1Layout.setHorizontalGroup(
            l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        l1Layout.setVerticalGroup(
            l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        homee.setText("HOME");
        homee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeeActionPerformed(evt);
            }
        });

        l2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l2Layout = new javax.swing.GroupLayout(l2);
        l2.setLayout(l2Layout);
        l2Layout.setHorizontalGroup(
            l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(l2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        l2Layout.setVerticalGroup(
            l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18)
        );

        l3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l3Layout = new javax.swing.GroupLayout(l3);
        l3.setLayout(l3Layout);
        l3Layout.setHorizontalGroup(
            l3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19)
        );
        l3Layout.setVerticalGroup(
            l3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19)
        );

        l4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l4Layout = new javax.swing.GroupLayout(l4);
        l4.setLayout(l4Layout);
        l4Layout.setHorizontalGroup(
            l4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20)
        );
        l4Layout.setVerticalGroup(
            l4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20)
        );

        l5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l5Layout = new javax.swing.GroupLayout(l5);
        l5.setLayout(l5Layout);
        l5Layout.setHorizontalGroup(
            l5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21)
        );
        l5Layout.setVerticalGroup(
            l5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21)
        );

        l6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l6Layout = new javax.swing.GroupLayout(l6);
        l6.setLayout(l6Layout);
        l6Layout.setHorizontalGroup(
            l6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22)
        );
        l6Layout.setVerticalGroup(
            l6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22)
        );

        l7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l7Layout = new javax.swing.GroupLayout(l7);
        l7.setLayout(l7Layout);
        l7Layout.setHorizontalGroup(
            l7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23)
        );
        l7Layout.setVerticalGroup(
            l7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23)
        );

        l8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l8Layout = new javax.swing.GroupLayout(l8);
        l8.setLayout(l8Layout);
        l8Layout.setHorizontalGroup(
            l8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24)
        );
        l8Layout.setVerticalGroup(
            l8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24)
        );

        l9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l9Layout = new javax.swing.GroupLayout(l9);
        l9.setLayout(l9Layout);
        l9Layout.setHorizontalGroup(
            l9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25)
        );
        l9Layout.setVerticalGroup(
            l9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25)
        );

        l10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l10Layout = new javax.swing.GroupLayout(l10);
        l10.setLayout(l10Layout);
        l10Layout.setHorizontalGroup(
            l10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26)
        );
        l10Layout.setVerticalGroup(
            l10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26)
        );

        l11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l11Layout = new javax.swing.GroupLayout(l11);
        l11.setLayout(l11Layout);
        l11Layout.setHorizontalGroup(
            l11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27)
        );
        l11Layout.setVerticalGroup(
            l11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27)
        );

        l12.setBackground(new java.awt.Color(0, 0, 0));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l12Layout = new javax.swing.GroupLayout(l12);
        l12.setLayout(l12Layout);
        l12Layout.setHorizontalGroup(
            l12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28)
        );
        l12Layout.setVerticalGroup(
            l12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28)
        );

        l13.setBackground(new java.awt.Color(0, 0, 0));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l13Layout = new javax.swing.GroupLayout(l13);
        l13.setLayout(l13Layout);
        l13Layout.setHorizontalGroup(
            l13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29)
        );
        l13Layout.setVerticalGroup(
            l13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29)
        );

        l14.setBackground(new java.awt.Color(0, 0, 0));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l14Layout = new javax.swing.GroupLayout(l14);
        l14.setLayout(l14Layout);
        l14Layout.setHorizontalGroup(
            l14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30)
        );
        l14Layout.setVerticalGroup(
            l14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30)
        );

        l15.setBackground(new java.awt.Color(0, 0, 0));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l15Layout = new javax.swing.GroupLayout(l15);
        l15.setLayout(l15Layout);
        l15Layout.setHorizontalGroup(
            l15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31)
        );
        l15Layout.setVerticalGroup(
            l15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31)
        );

        l16.setBackground(new java.awt.Color(0, 0, 0));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipart-asteroid-4.jpg"))); // NOI18N

        javax.swing.GroupLayout l16Layout = new javax.swing.GroupLayout(l16);
        l16.setLayout(l16Layout);
        l16Layout.setHorizontalGroup(
            l16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(l16Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        l16Layout.setVerticalGroup(
            l16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32)
        );

        click.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        click.setForeground(new java.awt.Color(255, 255, 255));
        click.setText("CLICK TO START");

        hsr.setForeground(new java.awt.Color(255, 255, 255));

        hsr1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        hsr1.setForeground(new java.awt.Color(255, 255, 255));
        hsr1.setText("HIGH SCORE:");

        hsr2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        hsr2.setForeground(new java.awt.Color(255, 255, 255));
        hsr2.setText("YOUR SCORE:");

        javax.swing.GroupLayout base1Layout = new javax.swing.GroupLayout(base1);
        base1.setLayout(base1Layout);
        base1Layout.setHorizontalGroup(
            base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, base1Layout.createSequentialGroup()
                .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(base1Layout.createSequentialGroup()
                        .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(base1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(homee))
                            .addGroup(base1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hsr2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(base1Layout.createSequentialGroup()
                                .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(l15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(base1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(hsr1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hsr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(base1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(bot1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(click)
                        .addGap(8, 8, 8)))
                .addGap(19, 19, 19))
        );
        base1Layout.setVerticalGroup(
            base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base1Layout.createSequentialGroup()
                .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(base1Layout.createSequentialGroup()
                        .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(base1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(base1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hsr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(base1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hsr2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(homee)))
                .addGroup(base1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(base1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(bot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, base1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(click, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void base1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_base1MouseReleased

        timer.stop();
        timer1.start();
    }//GEN-LAST:event_base1MouseReleased

    private void base1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_base1MousePressed

        click.setVisible(false);
        timer1.stop();
        timer.start();

        timer2.start();

    }//GEN-LAST:event_base1MousePressed

    private void homeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeeActionPerformed
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_homeeActionPerformed
  Timer timer=new Timer(1, new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            { 
                if(y<=1) 
            {
                reset();
            }
            
                
                y=(y-5);
               
         
                bot1.setBounds(290,y,30,20);
            }
        }
                );
  Timer timer1=new Timer(1, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {   if(y>=410) 
            {
                reset();
          
               
            }   
              
                y=(y+5);
                bot1.setBounds(290,y,30,20);
            }
        }
                );
 
   Timer timer2=new Timer(1, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                l1.setVisible(true);
                l2.setVisible(true);
                l3.setVisible(true);
                l4.setVisible(true);
                l5.setVisible(true);
                l6.setVisible(true);
                l7.setVisible(true);
                l8.setVisible(true);
                l1.setBounds(a--,s,30,30);
                l2.setBounds(b--,t,30,30);
                l3.setBounds(c--,u,30,30);
                l4.setBounds(d--,v,30,30);
                l5.setBounds(e1--,s1,30,30);
                l6.setBounds(f--,t1,30,30);
                l7.setBounds(g--,u1,30,30);
                l8.setBounds(h--,v1,30,30);
                if(((a>=280&&a<=310)&&(y>=s-15&&y<=s+15))||((b>=280&&b<=310)&&(y>=t-15&&y<=t+15))||((c>=280&&c<=310)&&(y>=u-15&&y<=u+15))||((d>=280&&d<=310)&&(y>=v-15&&y<=v+15))||((e1>=280&&e1<=310)&&(y>=s1-15&&y<=s1+15))||((f>=280&&f<=310)&&(y>=t1-15&&y<=t1+15))||((g>=280&&g<=310)&&(y>=u1-15&&y<=u1+15))||((h>=280&&h<=310)&&(y>=v1-15&&y<=v1+15)))
                {
                      reset();
                     }
                  if(d==0) 
                {
                    timer3.start();
                  
                }
                if(h==0) 
                {
                   
                    t2res();
                    
                }
               if(a==289||b==289||c==289||d==289||e1==289||f==289||g==289||h==289) 
               {
                   scr++;
                   score.setText(""+scr);
               }
                     
                
            }
        }
                );
    Timer timer3=new Timer(1, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                
                l9.setVisible(true);
                l10.setVisible(true);
                l11.setVisible(true);
                l12.setVisible(true);
                l13.setVisible(true);
                
                l14.setVisible(true);
                l15.setVisible(true);
                l16.setVisible(true);
                l9.setBounds(a1--,s2,30,30);
                l10.setBounds(b1--,t2,30,30);
                l11.setBounds(c1--,u2,30,30);
                l12.setBounds(d1--,v2,30,30);
                l13.setBounds(e11--,s3,30,30);
                l14.setBounds(f1--,t3,30,30);
                l15.setBounds(g1--,u3,30,30);
                l16.setBounds(h1--,v3,30,30);
                if(((a1>=275&&a1<=315)&&(y>=s2-15&&y<=s2+15))||((b1>=275&&b1<=315)&&(y>=t2-15&&y<=t2+15))||((c1>=275&&c1<=315)&&(y>=u2-15&&y<=u2+15))||((d1>=275&&d1<=315)&&(y>=v2-15&&y<=v2+15))||((e11>=275&&e11<=315)&&(y>=s3-15&&y<=s3+15))||((f1>=275&&f1<=315)&&(y>=t3-15&&y<=t3+15))||((g1>=275&&g1<=315)&&(y>=u3-15&&y<=u3+15))||((h1>=275&&h1<=315)&&(y>=v3-15&&y<=v3+15)))
                {
                     reset();
                   }
                     
            
                if(h1==0) 
                {
                   
                   
                    t3res();
                   
                }
                 if(a1==289||b1==289||c1==289||d1==289||e11==289||f1==289||g1==289||h1==289) 
               {
                   scr++;
                   score.setText(""+scr);
               }
            }
        }
                );
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jump().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base1;
    private javax.swing.JPanel bot1;
    private javax.swing.JLabel click;
    private javax.swing.JButton homee;
    private javax.swing.JLabel hsr;
    private javax.swing.JLabel hsr1;
    private javax.swing.JLabel hsr2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel l1;
    private javax.swing.JPanel l10;
    private javax.swing.JPanel l11;
    private javax.swing.JPanel l12;
    private javax.swing.JPanel l13;
    private javax.swing.JPanel l14;
    private javax.swing.JPanel l15;
    private javax.swing.JPanel l16;
    private javax.swing.JPanel l2;
    private javax.swing.JPanel l3;
    private javax.swing.JPanel l4;
    private javax.swing.JPanel l5;
    private javax.swing.JPanel l6;
    private javax.swing.JPanel l7;
    private javax.swing.JPanel l8;
    private javax.swing.JPanel l9;
    private javax.swing.JTextField score;
    // End of variables declaration//GEN-END:variables
}
